framework:
  http_client:
    scoped_clients:
      tmdb.client:
        base_uri: '%env(TMDB_API_URL)%'
        headers:
          Accept: 'application/json'
          Authorization: 'Bearer %env(TMDB_API_TOKEN)%'
