version: '3.8'
services:
  httpd:
    build:
      context: ./docker/httpd
      dockerfile: Dockerfile
    container_name: 'wemovies-httpd'
    hostname: 'wemovies-httpd'
    ports:
      - "80:80"
    volumes:
      - './:/app/'
      - './docker/httpd/wemovies.conf:/usr/local/apache2/conf/extra/wemovies.conf'
    working_dir: '/app'

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 'wemovies-php'
    hostname: 'wemovies-php'
    volumes:
      - './:/app/'
      - './docker/php/php.ini:/opt/bitnami/php/etc/php.ini'
    working_dir: '/app'

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: 'wemovies-node'
    hostname: wemovies-node
    volumes:
      - './:/app/'
    working_dir: '/app'
